[versions]
annotations = "26.0.2"
assertj-core = "3.27.3"
classgraph = "4.8.180"
diff-utils = "1.3.0"
durian = "1.2.0"
junit = "5.8.1"
maven-resolver = "2.0.13"
mockito = "5.17.0"
native-include-cleanThat = "2.23"
native-include-googleJavaFormat = "1.27.0"
native-include-palantirJavaFormat = "2.67.0"
# to find required version here check eclipse_wtp_formatter/v4.21.0.lockfile
# where <4.21.0> is the default version of com.diffplug.spotless.extra.wtp.EclipseWtpFormatterStep#defaultVersion
native-include-spotlessEclipseWtp = "3.23.0"
native-include-spotlessEclipseWtpFormatter = "4.21.0"
picocli = "4.7.6"
selfie = "2.5.5"
slf4j = "2.0.17"
spotless-lib = "4.1.0"
spotless-plugin-gradle = "8.1.0"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
diff-utils = { module = "com.googlecode.java-diff-utils:diffutils", version.ref = "diff-utils" }
durian-core = { module = "com.diffplug.durian:durian-core", version.ref = "durian" }
durian-io = { module = "com.diffplug.durian:durian-io", version.ref = "durian" }
durian-collect = { module = "com.diffplug.durian:durian-collect", version.ref = "durian" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
maven-resolver-api = { module = "org.apache.maven.resolver:maven-resolver-api" } # version from bom
maven-resolver-bom = { module = "org.apache.maven.resolver:maven-resolver", version.ref = "maven-resolver" }
maven-resolver-connector-basic = { module = "org.apache.maven.resolver:maven-resolver-connector-basic" } # version from bom
maven-resolver-impl = { module = "org.apache.maven.resolver:maven-resolver-impl" } # version from bom
maven-resolver-spi = { module = "org.apache.maven.resolver:maven-resolver-spi" } # version from bom
maven-resolver-supplier-mvn4 = { module = "org.apache.maven.resolver:maven-resolver-supplier-mvn4" } # version from bom
maven-resolver-transport-apache = { module = "org.apache.maven.resolver:maven-resolver-transport-apache" } # version from bom
maven-resolver-transport-file = { module = "org.apache.maven.resolver:maven-resolver-transport-file" } # version from bom
maven-resolver-util = { module = "org.apache.maven.resolver:maven-resolver-util" } # version from bom
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
native-include-cleanThat = { module = "io.github.solven-eu.cleanthat:java", version.ref = "native-include-cleanThat" }
native-include-googleJavaFormat = { module = "com.google.googlejavaformat:google-java-format", version.ref = "native-include-googleJavaFormat" }
native-include-palantirJavaFormat = { module = "com.palantir.javaformat:palantir-java-format", version.ref = "native-include-palantirJavaFormat" }
native-include-spotlessEclipseWtp = { module = "com.diffplug.spotless:spotless-eclipse-wtp", version.ref = "native-include-spotlessEclipseWtp" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
selfie = { module = "com.diffplug.selfie:selfie-runner-junit5", version.ref = "selfie" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-binding = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j" }
spotless-lib = { module = "com.diffplug.spotless:spotless-lib", version.ref = "spotless-lib" }
spotless-lib-extra = { module = "com.diffplug.spotless:spotless-lib-extra", version.ref = "spotless-lib" }
spotless-plugin-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless-plugin-gradle" }

[bundles]
durian-libs = ["durian-core", "durian-io", "durian-collect"]
maven-resolver-libs = [
    "maven-resolver-api",
    "maven-resolver-spi",
    "maven-resolver-util",
    "maven-resolver-impl",
    "maven-resolver-connector-basic",
    "maven-resolver-transport-file",
    "maven-resolver-transport-apache",
    "maven-resolver-supplier-mvn4",
]
native-includes = [
    "native-include-cleanThat",
    "native-include-googleJavaFormat",
    "native-include-palantirJavaFormat",
    "native-include-spotlessEclipseWtp",
]
spotless-libs = ["spotless-lib", "spotless-lib-extra"]
test-libs = ["assertj-core", "junit-jupiter-api", "selfie", "mockito"]
